# Generated by Django 3.2.16 on 2023-12-16 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_otp_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_otp',
        ),
        migrations.AddField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_otps', to='account.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_otps', to='account.otp'),
        ),
    ]
