# Generated by Django 3.2.16 on 2023-12-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_otp_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
