# Generated by Django 3.2.16 on 2023-12-16 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_delete_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
