# Generated by Django 3.2.16 on 2023-12-16 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20231216_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
    ]
