# Generated by Django 3.2.16 on 2024-09-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_blacklistedtoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
