# Generated by Django 3.2.16 on 2024-09-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_usertoken_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
