# Generated by Django 3.2.16 on 2024-09-06 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_usertoken_valid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertoken',
            old_name='valid',
            new_name='is_valid',
        ),
    ]
