# Generated by Django 3.2.16 on 2023-07-08 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship_no', models.CharField(max_length=255)),
                ('front_image', models.ImageField(blank=True, upload_to='employee_image')),
                ('back_image', models.ImageField(blank=True, upload_to='employee_image')),
            ],
            options={
                'verbose_name': 'Citizenship Information',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.CharField(max_length=255)),
                ('front_image', models.ImageField(blank=True, upload_to='employee_image')),
                ('back_image', models.ImageField(blank=True, upload_to='employee_image')),
            ],
            options={
                'verbose_name': 'License Information',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.IntegerField(blank=True, default=2, null=True)),
                ('contact_number', models.CharField(max_length=255)),
                ('alt_contact_number', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_number', models.CharField(max_length=255)),
                ('degination', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='employee_image')),
                ('address', models.CharField(max_length=255)),
                ('blood_group', models.CharField(blank=True, max_length=255, null=True)),
                ('email_addrress', models.EmailField(blank=True, max_length=255, null=True)),
                ('material_status', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=255, null=True)),
                ('citizenship_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hrm_system.citizenship')),
                ('license_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hrm_system.license')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Information',
                'db_table': 'sales_employee',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('address_line_1', models.CharField(max_length=200)),
                ('client_logo', models.ImageField(default='default_logo.jpg', upload_to='company_logos')),
                ('province', models.CharField(blank=True, choices=[('Province1', 'Province1'), ('Province2', 'Province2'), ('Proviance3', 'Proviance3')], max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=10, null=True)),
                ('contact_number', models.CharField(max_length=255)),
                ('email_addrress', models.CharField(blank=True, max_length=100, null=True)),
                ('pan_number', models.CharField(max_length=255)),
                ('vat_number', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=255)),
                ('unique_id', models.CharField(blank=True, max_length=200, null=True)),
                ('remarks', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Information',
                'db_table': 'tbl_client_informations',
                'ordering': ('-created_at',),
                'managed': True,
            },
        ),
    ]
