# Generated by Django 3.2.16 on 2023-07-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_system', '0002_alter_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pin_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
