# Generated by Django 3.2.16 on 2023-07-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_system', '0004_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
